# Generated by Django 2.2.3 on 2019-09-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190912_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-rating']},
        ),
    ]
